version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:22.3.13.5-alpine
    container_name: clickhouse
    ports:
      - "9000:9000"
      - "8123:8123"
    environment:
      - CLICKHOUSE_DB=signoz_traces
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    command: ["--config-file=/etc/clickhouse-server/config.xml"]

  otel-collector:
    image: otel/opentelemetry-collector:0.96.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
    depends_on:
      - clickhouse

  query-service:
    image: signoz/query-service:0.48.0
    container_name: query-service
    ports:
      - "8080:8080"
    environment:
      - SIGNOZ_DB_DSN=clickhouse://clickhouse:9000?database=signoz_traces
      - SIGNOZ_REDIS_URL=redis://redis:6379
    depends_on:
      - clickhouse
      - redis

  frontend:
    image: signoz/frontend:0.48.0
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080
    depends_on:
      - query-service

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  clickhouse-data: 